
    /* eslint-disable */
    /* tslint:disable */
    // @ts-nocheck
    // This class is auto-generated by Plasmic; please do not edit!
    // Plasmic Project: 21yfH8a5FQ3G5YYAEZCSx

    

    import * as React from "react"
    import {hasVariant, ensureGlobalVariants} from "@plasmicapp/react-web";
    import { CompE7ZEv8GAkfqT } from "./CompE7ZEv8GAkfqT";  // plasmic-import: E7ZEv8GAkfqT/codeComponent
    

    export interface GlobalContextsProviderProps {
      children?: React.ReactElement;
      userSessionProps?: Partial<
           Omit<React.ComponentProps<typeof CompE7ZEv8GAkfqT>, "children">>;
    }

    export default function GlobalContextsProvider(props: GlobalContextsProviderProps) {
      
      const {
        children,
        userSessionProps
      } = props;

      
      return (
      <CompE7ZEv8GAkfqT
      {...userSessionProps}
      
      >
        { children }
      </CompE7ZEv8GAkfqT>
    )
    }
  