
    /* eslint-disable */
    /* tslint:disable */
    // @ts-nocheck
    // This class is auto-generated by Plasmic; please do not edit!
    // Plasmic Project: 4u1ey5YPrV7Q3hoMkXvHtk

    

    import * as React from "react"
    import {hasVariant, ensureGlobalVariants} from "@plasmicapp/react-web";
    import { UserSession } from "./UserSession";  // plasmic-import: jmq0onPiAKjW/codeComponent
    

    export interface GlobalContextsProviderProps {
      children?: React.ReactElement;
      userSessionProps?: Partial<
           Omit<React.ComponentProps<typeof UserSession>, "children">>;
    }

    export default function GlobalContextsProvider(props: GlobalContextsProviderProps) {
      
      const {
        children,
        userSessionProps
      } = props;

      
      return (
      <UserSession
      {...userSessionProps}
      
      >
        { children }
      </UserSession>
    )
    }
  